agent:
  # Number of episodes (kaç bölüm (gün) eğitileceği)
  num_episodes: 1460
  # Maximum number of time steps in each episode (bir bölümdeki step sayısı (saat))
  horizon: 24
  # Discount factor
  gamma: 0.99
  # Number of tiles for tile coding (fayanslama yani tile işlemi için fayans sayısı) fayanslama işlemi sürekli değişkenleri parçalayarak ajanın daha rahat öğrenmesini sağlar
  num_tiles: 20
  # Initial value for Epsilon (rastgele hamle yapma olasılığı)
  initial_epsilon: 1
  # Annealing rate for Epsilon (olasılığı düşürme katsayısı)
  epsilon_annealing: 0.999
  # Initial learning rate (öğrenme oranı. bu oran yüksek olursa istikrarsızlığa yol açabilir.) düşük olursa değerleri güncelleme yüzdesi az olur ve istikrarsızlık azalır
  learning_rate: 0.1
  # Annealing rate for learning rate (öğrenme yüzdesini düşürme katsayısı)
  learning_rate_annealing: 0.999

env:
  # Sinergym environment ismi. Bu isme göre oluşturacağımız mekanı da seçmiş oluyoruz
  name: Eplus-5Zone-hot-discrete-v1
  # Whether to normalise observations
  normalize: True
  # The observation variables to use for training, offset by 4 to account for time vars
  obs_to_keep: [0, 1, 8, 10]
  # izlenebilir değişkenlerin türleri:
  #   0 - yavaş değişen değişkenler
  #   1 - hızlı değişen değişkenler
  #   2 - ayrık değişkenler
  mask: [0, 0, 0, 0]